server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'gateway,*'
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: vehicles.ms
          uri: lb://vehicles.ms:8090
          predicates:
            - Path=/api/vehicles/**
        - id: repairs-list.ms
          uri: lb://repairs-list.ms:8091
          predicates:
            - Path=/api/repairs_types/**
        - id: repairs_vehicle.ms
          uri: lb://repairs_vehicle.ms:8092
          predicates:
            - Path=/api/repairs_vehicles/**