server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: vehicles.ms
          uri: lb://vehicles.ms:8090
          predicates:
            - Path=/api/vehicles/**
        - id: repairs_list.ms
          uri: lb://repair_list.ms:8091
          predicates:
            - Path=/api/repair_prices/**
            - Path=/api/repair_types/**