server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/repair-vehicle-db
    username: postgres
    password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/