server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://repairs-list-db:5434
    username: postgres
    password: 123456
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://host.docker.internal:8761/eureka/