server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicles_MS
    username: postgres
    password: 123456
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/