apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_VEHICLES: "vehicles.ms-service"
  DB_PORT_VEHICLES: "5432"
  DB_DBNAME_VEHICLES: "vehicles_MS"
  DB_USER: "postgres"
  DB_PASSWORD: "123456"

